export const fetchFile = {
  FILE_SECTION_PATH_FETCH_REQUESTED: 'FILE_SECTION_PATH_FETCH_REQUESTED',
  FILE_SECTION_PATH_FETCH_FAILED: 'FILE_SECTION_PATH_FETCH_FAILED',
  FILE_SECTION_PATH_FETCH_SUCCEEDED: 'FILE_SECTION_PATH_FETCH_SUCCEEDED',
};

export const fetchText = {
  ADD_TEXT: 'ADD_TEXT',
  FETCH_TEXT_REQUESTED: 'FETCH_TEXT_REQUESTED',
  FETCH_TEXT_FAILED: 'FETCH_TEXT_FAILED',
  FETCH_TEXT_SUCCEEDED: 'FETCH_TEXT_SUCCEEDED',
};
