export const fetchFile = {
  FILE_SECTIONS_FETCH_REQUESTED: 'FILE_SECTIONS_FETCH_REQUESTED',
  FILE_SECTIONS_FETCH_FAILED: 'FILE_SECTIONS_FETCH_FAILED',
  FILE_SECTIONS_FETCH_SUCCEEDED: 'FILE_SECTIONS_FETCH_SUCCEEDED',
};

export const fetchSections = {
  ADD_DROP_SECTION: 'ADD_DROP_SECTION',
  FETCH_EMAIL_REQUESTED: 'FETCH_EMAIL_REQUESTED',
  FETCH_EMAIL_FAILED: 'FETCH_EMAIL_FAILED',
  FETCH_EMAIL_SUCCEEDED: 'FETCH_EMAIL_SUCCEEDED',
  SAVE_EMAIL_REQUESTED: 'SAVE_EMAIL_REQUESTED',
  SAVE_EMAIL_SUCCEEDED: 'SAVE_EMAIL_SUCCEEDED',
  SAVE_EMAIL_FAILED: 'SAVE_EMAIL_FAILED',
};

export const ui = {
  GET_USER_ID: 'GET_USER_ID',
  GET_USER_ID_FAILED: 'GET_USER_ID_FAILED',
  GET_USER_ID_SUCCEEDED: 'GET_USER_ID_SUCCEEDED',
};
